export type FinanceErrorCode =
  | 'FINANCE_TENANT_REQUIRED'
  | 'FINANCE_ORGANIZATION_NOT_FOUND'
  | 'FINANCE_NOT_ACTIVE'
  | 'FINANCE_OWNER_REQUIRED'
  | 'FINANCE_ONBOARDING_ALREADY_COMPLETED'
  | 'FINANCE_LIFECYCLE_CONFLICT'
  | 'FINANCE_ACCOUNT_NOT_SELECTABLE'
  | 'FINANCE_ACCOUNT_NOT_FOUND'
  | 'FINANCE_JOURNAL_ACCOUNT_NOT_SELECTABLE'
  | 'FINANCE_JOURNAL_IDEMPOTENCY_CONFLICT'
  | 'FINANCE_JOURNAL_CREATE_CONFLICT'
  | 'FINANCE_JOURNAL_NOT_FOUND'
  | 'FINANCE_JOURNAL_NOT_REVERSIBLE'
  | 'FINANCE_JOURNAL_REVERSAL_CONFLICT'
  | 'FINANCE_JOURNAL_REVERSAL_FINALIZATION_FAILED'
  | 'FINANCE_SALES_SOURCE_TENANT_CONFLICT'
  | 'FINANCE_SALES_ACCOUNT_MAPPING_MISSING'
  | 'FINANCE_SALES_TRANSACTION_NOT_FOUND'
  | 'FINANCE_SALES_TRANSACTION_NOT_POSTABLE'
  | 'FINANCE_INVENTORY_LOCATION_NOT_FOUND'
  | 'FINANCE_INVENTORY_ITEM_NOT_FOUND'
  | 'FINANCE_INVENTORY_QUANTITY_NOT_TRACKED'
  | 'FINANCE_INVENTORY_VALUE_COST_REQUIRED'
  | 'FINANCE_INVENTORY_NEGATIVE_STOCK'
  | 'FINANCE_INVENTORY_BALANCE_UNRESOLVED'
  | 'FINANCE_INVENTORY_BALANCE_COST_MISSING'
  | 'FINANCE_INVENTORY_ADJUSTMENT_ACCOUNT_NOT_CONFIGURED'
  | 'FINANCE_INVENTORY_ADJUSTMENT_ACCOUNT_INVALID'
  | 'FINANCE_INVENTORY_ADJUSTMENT_IDEMPOTENCY_CONFLICT'
  | 'FINANCE_INVENTORY_ADJUSTMENT_FINALIZATION_FAILED'
  | 'FINANCE_INVENTORY_COGS_FINALIZATION_FAILED'
  | 'FINANCE_INVENTORY_COGS_REVERSAL_FAILED'
  | 'FINANCE_CASH_BANK_TRANSFER_ACCOUNT_INVALID'
  | 'FINANCE_CASH_BANK_TRANSFER_IDEMPOTENCY_CONFLICT'
  | 'FINANCE_CASH_BANK_TRANSFER_FINALIZATION_FAILED'
  | 'FINANCE_PERIOD_INVALID'
  | 'FINANCE_PERIOD_ACTOR_INVALID'
  | 'FINANCE_PERIOD_NOT_OPEN'
  | 'FINANCE_PERIOD_DATE_OUTSIDE_RANGE'
  | 'FINANCE_PERIOD_ALREADY_CLOSED'
  | 'FINANCE_PERIOD_CLOSE_CONFLICT';

export class FinanceDomainError extends Error {
  readonly code: FinanceErrorCode;

  constructor(message: string, code: FinanceErrorCode) {
    super(message);
    this.name = 'FinanceDomainError';
    this.code = code;
  }
}
