import z from 'zod';

export const CreateReportSchema = z.object({
  startDate: z.string(),
  endDate: z.string(),
});

export const SalesReportResponseSchema = z.object({
  // total_profit: z.number(),
  total_gross_profit: z.number(),
  total_net_profit: z.number(),
  total_revenue: z.number(),
  ratio_profit_to_revenue: z.number(),
  total_payout: z.number(),
  // total_gross_profit: z.number(),
  total_payment: z.number(),
  total_cost: z.number(),
  total_voucher_borne_by_seller: z.number(),
  total_bundle_deal_discount_from_seller: z.number(),
  total_shipping_cost_paid_by_buyer: z.number(),
  total_admin_fee: z.number(),
  total_processing_fee: z.number(),
  total_orders: z.number(),
  total_buyers: z.number(),
  total_orders_confirmed: z.number(),
  total_orders_cancelled: z.number(),
  daily_reports: z.array(
    z.object({
      day: z.number(),
      month: z.number(),
      year: z.number(),
      daily_revenue: z.number(),
      daily_payout: z.number(),
      // daily_profit: z.number(),
      daily_gross_profit: z.number(),
      daily_net_profit: z.number(),
      daily_payment: z.number(),
      daily_cost: z.number(),
      number_of_orders: z.number(),
      total_orders_confirmed: z.number(),
      total_orders_cancelled: z.number(),
      orders: z.array(
        z.object({
          order_id: z.string(),
          username: z.string(),
          status: z.string(),
          placed_at: z.string(),
          // total_profit: z.number(),
          total_gross_profit: z.number(),
          total_net_profit: z.number(),
          total_payment: z.number(),
          subtotal: z.number(),
        })
      ),
    })
  ),
});

export const ProductAnalyticsRowSchema = z.object({
  product_id: z.string().nullable().optional(),
  product_name: z.string(),
  variation_id: z.string().nullable().optional(),
  variation_name: z.string().nullable().optional(),
  parent_sku: z.string().nullable().optional(),
  child_sku: z.string().nullable().optional(),
  orders: z.number(),
  units: z.number(),
  returned_units: z.number(),
  gross_sales: z.number(),
  discount: z.number(),
  net_sales: z.number(),
  cogs: z.number(),
  gross_profit: z.number(),
  platform_fee: z.number(),
  shipping_cost: z.number(),
  other_variable_cost: z.number(),
  marketplace_deduction: z.number(),
  net_profit: z.number(),
  gross_margin: z.number(),
  net_margin: z.number(),
  profit_per_unit: z.number(),
  sales_contribution: z.number(),
  profit_contribution: z.number(),
  unit_contribution: z.number(),
  order_contribution: z.number(),
  sales_rank: z.number(),
  profit_rank: z.number(),
  units_rank: z.number(),
  sales_per_day: z.number(),
  units_per_day: z.number(),
  orders_per_day: z.number(),
  profit_per_day: z.number(),
  classification: z.enum([
    'Star',
    'Revenue Driver',
    'Profit Driver',
    'Weak',
  ]),
});

export const ProductAnalyticsSummarySchema = z.object({
  total_products: z.number(),
  total_orders: z.number(),
  total_units: z.number(),
  returned_units: z.number(),
  gross_sales: z.number(),
  discount: z.number(),
  net_sales: z.number(),
  cogs: z.number(),
  gross_profit: z.number(),
  platform_fee: z.number(),
  shipping_cost: z.number(),
  other_variable_cost: z.number(),
  marketplace_deduction: z.number(),
  net_profit: z.number(),
  gross_margin: z.number(),
  net_margin: z.number(),
});

export const ProductAnalyticsResponseSchema = z.object({
  summary: ProductAnalyticsSummarySchema,
  products: z.array(ProductAnalyticsRowSchema),
  meta: z.object({
    total_products: z.number(),
    start_date: z.string().nullable(),
    end_date: z.string().nullable(),
    period_days: z.number(),
  }),
});
